import Head from "next/head";

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <div>
      <Head>
        <title>미적분 계산기</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="grid grid-cols-12 h-screen">
        <div className="col-span-2 bg-slate-200 h-full shadow-2xl border-r-[1px] border-r-slate-300/75 px-5 py-5">
          <div>
            <div className="text-xl font-semibold pb-1 uppercase">
              Calculus Sandbox
            </div>
            <div className="text-gray-500 text-sm">미적분 계산기</div>
          </div>
          <hr className="w-full border-b-[1px] border-gray-300/50 my-2" />
          <div className="bg-slate-300/60 px-3 py-2 rounded-lg">
            양함수 미분기
          </div>
        </div>
        <div className="col-span-10 px-8 py-6 h-screen overflow-y-scroll">
          {children}
        </div>
      </div>
    </div>
  );
}
